[project]
name = "snapshot"
version = "0.1.0"
authors = [{ name = "Charlie" }, { name = "Aaron" }]

dependencies = [
    "pydantic",
    "pydantic_settings",
    "twilio",
    "sqlalchemy",
    "fastapi[standard]",
    "black",
    "isort",
]

[tool.isort]
profile = "black"
